### ISSUE TITLE
Error in loader

### ISSUE THREAD

**Issue by juniorschen** [danvick/ngx-translate-nativescript-loader#5]
My version:
![image](https://user-images.githubusercontent.com/46031261/90432515-05ce8b00-e0a1-11ea-911a-1829c3c365bb.png)
Error:
![image](https://user-images.githubusercontent.com/46031261/90432478-f51e1500-e0a0-11ea-9404-8db63d71a9db.png)

**Comment by benco8186** [comment]
Same error

**Comment by juniorschen** [comment]
@benco8186  i fixed creating the loader on my app
![image](https://user-images.githubusercontent.com/46031261/90914771-cd86bf80-e3b4-11ea-9486-6cc317799034.png)

**Comment by benco8186** [comment]
i fixed too lol but in a different way, i also have created my own implementation but just with a copy/past it doesn't work.
I changed a little bit the code and now it works : 

import { TranslateLoader } from '@ngx-translate/core';
import { knownFolders } from 'tns-core-modules/file-system';
import { from, Observable } from 'rxjs';
import { map } from 'rxjs/operators';

export class NativeScriptLoader implements TranslateLoader {

    constructor(public prefix: string = '/assets/i18n/', public suffix: string = '.json') {
    }

    public getTranslation(lang: string): Observable<any> {
        return from(knownFolders.currentApp().getFile(`${this.prefix}${lang}${this.suffix}`).readText()).pipe(
            map((data: any) => JSON.parse(data))
        );
    }
}
